# Generated by Django 6.0.3 on 2026-06-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_movie_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='max_center_seats_per_row',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
