# Generated by Django 6.0.3 on 2026-06-18 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0015_seed_sessions_june_2026"),
        ("catalog", "0016_room_accessible_row_index"),
    ]

    operations = []
