# Generated by Django 6.0.3 on 2026-06-20 21:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_movie_spotlight_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'movie_reviews',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('movie', 'user'), name='unique_movie_review_per_user'), models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='movie_review_rating_1_to_5')],
            },
        ),
    ]
