# Generated by Django 6.0.3 on 2026-06-21 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_review_half_star_and_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='classification_description',
            field=models.TextField(blank=True, default='', verbose_name='Descrição da classificação'),
        ),
    ]
