# Generated by Codex on 2026-06-02

from django.db import migrations


def normalize_session_seat_statuses(apps, schema_editor):
    SessionSeat = apps.get_model("reservations", "SessionSeat")

    status_map = {
        "available": "AVAILABLE",
        "reserved": "RESERVED",
        "purchased": "PURCHASED",
    }

    for legacy_status, normalized_status in status_map.items():
        SessionSeat.objects.filter(status=legacy_status).update(
            status=normalized_status
        )


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0006_ticket_pricing_fields"),
    ]

    operations = [
        migrations.RunPython(
            code=normalize_session_seat_statuses,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
