# Generated by Django 6.0.3 on 2026-06-16 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0007_normalize_session_seat_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="seat",
            name="companion_seat",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="paired_by",
                to="reservations.seat",
            ),
        ),
    ]
