# Generated by Django 6.0.3 on 2026-06-18 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0009_seed_session_seats_for_seeded_sessions"),
        ("reservations", "0011_create_pcd_rows_and_move_accessible_seats"),
    ]

    operations = []
