# Generated by Django 6.0.3 on 2026-06-19 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0012_merge_20260618_0019"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="ticket_type",
            field=models.CharField(
                choices=[
                    ("inteira", "Inteira"),
                    ("meia", "Meia"),
                    ("gratuito", "Gratuito"),
                ],
                default="inteira",
                max_length=20,
            ),
        ),
    ]
