# Generated by Django 6.0.3 on 2026-06-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_adminpermissionlog_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_protected_master",
            field=models.BooleanField(default=False),
        ),
    ]
